export const loginActionType = {
    SUCCESS_ACTION: "LOGIN_SUCCESS_ACTION",
    REQUEST_ACTION: "LOGIN_REQUEST_ACTION",
    FAILED_ACTION: "LOGIN_FAILED_ACTION"
}

export const adminUpdateActionType = {
    SUCCESS_ACTION: 'UPDATE_SUCCESS_ACTION',
    REQUEST_ACTION: 'UPDATE_REQUEST_ACTION',
    FAILED_ACTION: 'UPDATE_FAILED_ACTION'
}

export const schoolSaveActionType = {
    SUCCESS_ACTION: 'SCHOOL_SUCCESS_ACTION',
    REQUEST_ACTION: 'SCHOOL_REQUEST_ACTION',
    FAILED_ACTION: 'SCHOOL_FAILED_ACTION'
}

export const schoolUpdateActionType = {
    SUCCESS_ACTION: 'SCHOOL_UPDATE_SUCCESS_ACTION',
    REQUEST_ACTION: 'SCHOOL_UPDATE_REQUEST_ACTION',
    FAILED_ACTION: 'SCHOOL_UPDATE_FAILED_ACTION'
}
